<?xml version="1.0" encoding="utf-8"?><Database Name="TVC" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RODRIGUEZQUINTE\SQLEXPRESS;Initial Catalog=TVC;Persist Security Info=True;User ID=USR_TVC" SettingsObjectName="CargueMasivo.My.MySettings" SettingsPropertyName="TVCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.S_CGA" Member="S_CGA">
    <Type Name="S_CGA">
      <Column Name="Centro_ID" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Operacion_ID" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Orden_ID" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Puestotrabajo_ID" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COOIS_O_ActivNotificada_1" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="COOIS_O_ActivNotificada_2" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="COOIS_O_CantidadOperacion" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="COOIS_O_FechaFinMasTardia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COOIS_O_StatusSistema" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="COOIS_O_Txt_brv_Operacion" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="COOIS_O_ValorPrefijado_1" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="COOIS_O_ValorPrefijado_2" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="COOIS_P_Autor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="COOIS_P_CantidadOrden" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="COOIS_P_ClaseOrden" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="COOIS_P_ElementoPEP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="COOIS_P_Fechaentrada" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COOIS_P_FechaLiberacReal" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COOIS_P_HoraCreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="COOIS_P_ModificadoPor" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="COOIS_P_NumeroMaterial" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="COOIS_P_Orden" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="COOIS_P_Pedidocliente" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="COOIS_P_PosPedidoCliente" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="COOIS_P_StatusSistema" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="COOIS_P_TextoBreve" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="COOIS_P_TextoBreveMaterial" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="KSB1_Cantidad" Type="System.Decimal" DbType="Decimal(4,3)" CanBeNull="true" />
      <Column Name="KSB1_Cccoste" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="KSB1_ClAct" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="KSB1_CtdReg" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="KSB1_Denomin" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="KSB1_DenominacionObjeto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="KSB1_FeContab" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="KSB1_N_pers" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="KSB1_OrdPartner" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="KSB1_Usuario" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ZCOMCLI_CantidadPedido" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_CodMaterial" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_Entrega" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_EstatusOrden" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ZCOMCLI_FechaCreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZCOMCLI_FechaPreferenciaEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZCOMCLI_FechaRegEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZCOMCLI_FechaSalidaMat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZCOMCLI_HoraRegEntrega" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZCOMCLI_HoraSalidaMat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZCOMCLI_Material" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZCOMCLI_Moneda" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ZCOMCLI_N_Reparto" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_NombreCilente" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="ZCOMCLI_OrdenProduccion" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_Pedido" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_PetBorrado" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="ZCOMCLI_PosicionDoc" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZCOMCLI_Unidad" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ZCOMCLI_ValorPedido" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="ZPP078_Alistamiento" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP078_Clase" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ZPP078_Cliente" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP078_Duracmin" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP078_FechaFin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZPP078_FechaIni" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZPP078_HoraFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZPP078_HoraIni" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZPP078_N_Incid" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="ZPP078_N_Pedido" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZPP078_N_Personal" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZPP078_NC" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="ZPP078_Nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZPP078_NombrePersonal" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="ZPP078_OK" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP078_Posicion" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZPP078_StatusOrden" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZPP078_TiempoEfectivo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP078_TiempoPlan" Type="System.Decimal" DbType="Decimal(7,0)" CanBeNull="true" />
      <Column Name="ZPP079_DescMotivo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ZPP079_Duracmin" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZPP079_FechaFin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZPP079_FechaIni" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZPP079_HoraFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZPP079_HoraIni" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZPP079_Motivo" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ZPP079_N_Personal" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZPP079_NombrePersonal" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ZSD023_CreadoEl" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD023_CtdPed" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZSD023_Denominacion_1" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ZSD023_Denominacion_2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZSD023_DocVenta" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZSD023_DocVenta_1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="ZSD023_DocVenta_2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="ZSD023_FeEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD023_GClt" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ZSD023_Gr_1" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ZSD023_Gr_2" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ZSD023_LineaMecanizado" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZSD023_Material" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="ZSD023_Mon" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ZSD023_Nombre1" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZSD023_OfVta" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZSD023_PorcentajeRentabil" Type="System.Decimal" DbType="Decimal(5,3)" CanBeNull="true" />
      <Column Name="ZSD023_Rentabilid" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="ZSD023_Solic" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="ZSD023_Status" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="ZSD023_TpCambio" Type="System.Decimal" DbType="Decimal(7,0)" CanBeNull="true" />
      <Column Name="ZSD023_UM" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ZSD023_ValorNeto" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="ZSD023_VendedorEspecialista" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZSD023_VendedorInterno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZSD040_2_Cantidad" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_CodigoCli" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_Descr" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ZSD040_2_FecCot" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FecCre" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FechaCier" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FechaEnt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FecNE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FecOP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_FecPre" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ZSD040_2_HoraCrea" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSD040_2_HoraCT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSD040_2_HoraEnt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSD040_2_HoraNota" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSD040_2_Indicador" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ZSD040_2_LineaMat" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_Material" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_Nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ZSD040_2_NotaEntre" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_OrdenP" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_Pedido" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_Posicion" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="ZSD040_2_T_Ped" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ZSD040_2_Unidad" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ZSD040_2_Valor" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="GRPMaquina_ID" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>